### PR TITLE
Add endpoint GET dependencies by repository #11208

### PR DESCRIPTION
**Pull request by nbcraft**
@olegzd @pnavarrc

### CODE REVIEW

**Comment by steinheber** [comment]
@nbcraft , is this endpoint functional yet ? 
Was trying to execute against it without success.

**Comment by pnavarrc** [comment]
Hi @steinheber, the endpoint is functional. Are you still experiencing issues?

**Comment by steinheber** [comment]
I guess the point is that i am accessing zenhub enterprise =(

**Comment by nbcraft** [comment]
Hi @steinheber, the endpoint will be available in the next Zenhub Enterprise release.
We’ll keep you updated on when to expect the next release! Thank you.
(cc @kendramoroz)

**Comment by kendramoroz** [comment]
👋 Hey @steinheber we launched a new version of ZenHub Enterprise, 2.27 which contains the Dependency endpoints! Can you ping us at support@zenhub.com with what team you're on and we can follow-up with the admins to ensure the team upgrades to get you the endpoints :)?

**Pull request merged**
